<?php
  /**
   * @file
   * Rewrite images URLS from staging/development to production
   * so images do not have to be copied and to save disk space
   */

  /**
   * Admin module config form
   *
   * @Implement hook_config_form to create configuration form
   *
   * @param $form
   * @param $form_state
   *
   * @return Form structure
   */
  function staging_url_rewriter_form($form, &$form_state) {
    $settings = _staging_url_rewriter_get_settings();

    $isDebug = $settings['webform_dynamic_email_debug'];

    if ($isDebug) {
      dpm($settings, "Settings");
    }

    $form['staging_url_rewriter_production_url'] = array(
      '#type'          => 'textfield',
      '#title'         => t('Production URL'),
      '#description'   => t(
        'This is the base URL of the production site to try if images result in an error on this site.'
      ),
      '#default_value' => $settings['staging_url_rewriter_production_url'],
      '#size'          => 100,
      '#maxlength'     => 150,
      '#required'      => TRUE,
    );

    $form['staging_url_rewriter_debug'] = array(
      '#type'          => 'checkbox',
      '#title'         => t('Debug Mode'),
      '#default_value' => $settings['staging_url_rewriter_debug'],
      '#description'   => t(
        'Enable debug mode and display technical information on front end'
      ),
      '#required'      => FALSE,
    );

    return system_settings_form($form);
  }

  /**
   * @Implement hook_menu
   * Create configuration menu item on Admin page
   * @return array
   */
  function staging_url_rewriter_menu() {
    $items = array();

    $items['admin/config/staging_url_replacment_settings'] = array(
      'title'            => 'Staging URL Replacement Preferences',
      'description'      => 'Configuration for replacing URL with production URL when images are broken',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('staging_url_rewriter_form'),
      'access arguments' => array('access administration pages'),
      'type'             => MENU_NORMAL_ITEM,
    );

    return $items;
  }

  /**
   * Get the settings
   *
   * @array of
   *        settings[staging_url_rewriter_production_url,staging_url_rewriter_debug]
   */
  function _staging_url_rewriter_get_settings() {
    $settings = array();

    $settings['staging_url_rewriter_production_url'] = \Drupal::config('staging_url_rewriter.settings')
      ->get('staging_url_rewriter_production_url');
    if (empty($settings['staging_url_rewriter_production_url'])) {
      //$config = \Drupal::config('staging_url_rewriter.settings');
      $config =
        \Drupal::configFactory()
          ->getEditable('staging_url_rewriter.settings');
      $config->get('staging_url_rewriter_production_url');
      $config->set('staging_url_rewriter_production_url', _staging_url_rewriter_get_defualt_production_url())
        ->save();
      $settings['staging_url_rewriter_production_url'] = $config->get('staging_url_rewriter_production_url');
    }
    $settings['staging_url_rewriter_debug'] = \Drupal::config('staging_url_rewriter.settings')
      ->get('staging_url_rewriter_debug');

    return $settings;
  }

  /**
   * Implements hook_page_attachments().
   */
  function staging_url_rewriter_page_attachments(&$attachments) {
    //Only add attachments on non-admin pages
    if(!_staging_url_rewriter_is_admin_route()) {
      $settings = _staging_url_rewriter_get_settings();

      $attachments['#attached']['drupalSettings']['staging_url_rewriter'] = $settings;
      $attachments['#attached']['library'][]                              = 'staging_url_rewriter/rewrite_url_js';
    }

  }

  /**
   * Set default production url value
   * Implements hook_install().
   *
   */
  function staging_url_rewriter_install() {
    \Drupal::configFactory()->getEditable('staging_url_rewriter.production_url')
      ->set('staging_url_rewriter', _staging_url_rewriter_get_defualt_production_url())
      ->save();
  }

  /**
   * Remove update. and staging. from current from the current URL
   *
   * @return string
   */
  function _staging_url_rewriter_get_defualt_production_url() {
    global $base_url;

    $default_production_url = $base_url;
    $default_production_url = str_replace(
      "update.",
      "",
      $default_production_url
    );
    $default_production_url = str_replace(
      "staging.",
      "",
      $default_production_url
    );

    return $default_production_url;
  }

  /**
   * Check to see if the current route is an admin route
   * @return Bool
   */
  function _staging_url_rewriter_is_admin_route() {
    $route    = \Drupal::routeMatch()->getRouteObject();
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);
    return $is_admin;
  }