<?php

  /**
   * Attach Javascript on non-admin pages to allow for URL rewriting
   * Implements hook_page_attachments().
   */
  function staging_url_rewriter_page_attachments(&$attachments) {
    //Only add attachments on non-admin pages
    if (!\Drupal\staging_url_rewriter\StagingUrlRewriter::isAdminPath()) {
      $settings                                                           = \Drupal\staging_url_rewriter\StagingUrlRewriter::getSettings();
      $attachments['#attached']['drupalSettings']['staging_url_rewriter'] = $settings;
      $attachments['#attached']['library'][]                              = 'staging_url_rewriter/rewrite_url_js';
    }
  }
